AWSTemplateFormatVersion: '2010-09-09'
Description: An EC2 instance with Apache installation, user creation, KMS, EBS, private IP, and subnet using an existing security group

Parameters:
  ExistingSecurityGroupId:
    Description: "ID of an existing Security Group"
    Type: String
    AllowedPattern: "sg-[a-zA-Z0-9]+"
    ConstraintDescription: "Must be a valid security group ID."

  NewUserName:
    Description: "Name of the new user to create"
    Type: String
    Default: "newuser"

  NewUserPassword:
    Description: "Password for the new user"
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    ConstraintDescription: "Password must be between 8 and 32 characters."

  SubnetId:
    Description: "The subnet ID where the instance will be deployed"
    Type: AWS::EC2::Subnet::Id

  PrivateIpAddress:
    Description: "The private IP address to associate with the instance"
    Type: String

  KmsKeyId:
    Description: "The ID of the KMS key for EBS volume encryption"
    Type: String

  EbsVolumeSize:
    Description: "The size of the EBS volume in GB"
    Type: Number
    Default: 20
    MinValue: 1
    MaxValue: 16384

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      KeyName: my-key-pair
      ImageId: ami-0abcdef1234567890
      SubnetId: !Ref SubnetId
      PrivateIpAddress: !Ref PrivateIpAddress
      SecurityGroupIds: 
        - !Ref ExistingSecurityGroupId
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref EbsVolumeSize
            VolumeType: gp2
            Encrypted: true
            KmsKeyId: !Ref KmsKeyId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><h1>Hello from your EC2 instance!</h1></html>" > /var/www/html/index.html
          useradd ${NewUserName}
          echo ${NewUserName}:${NewUserPassword} | chpasswd
